DROP TABLE app_users IF EXISTS;
DROP TABLE roles IF EXISTS;

CREATE TABLE app_users (
  USER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  );